// -*- Mode: Go; indent-tabs-mode: t -*-

/*
 * Copyright (C) Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package ldconfig

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/snapcore/snapd/dirs"
	"github.com/snapcore/snapd/interfaces"
	"github.com/snapcore/snapd/osutil"
	"github.com/snapcore/snapd/timings"
)

// Backend is responsible for maintaining ldconfig cache.
type Backend struct{}

var _ = interfaces.SecurityBackend(&Backend{})

// Initialize does nothing for this backend.
func (b *Backend) Initialize(opts *interfaces.SecurityBackendOptions) error {
	return nil
}

// Name returns the name of the backend.
func (b *Backend) Name() interfaces.SecuritySystem {
	return "ldconfig"
}

// Setup will make the ldconfig backend generate the needed
// configuration files and re-create the ld cache.
//
// If the method fails it should be re-tried (with a sensible strategy) by the caller.
func (b *Backend) Setup(appSet *interfaces.SnapAppSet, opts interfaces.ConfinementOptions, repo *interfaces.Repository, tm timings.Measurer) error {
	snapName := appSet.InstanceName()
	// Get the snippets that apply to this snap
	spec, err := repo.SnapSpecification(b.Name(), appSet, opts)
	if err != nil {
		return fmt.Errorf("cannot obtain ldconfig specification for snap %q: %s", snapName, err)
	}

	return b.setupLdconfigCache(spec.(*Specification))
}

// Remove removes modules ldconfig file specific to a given snap.
// This method should be called after removing a snap.
//
// If the method fails it should be re-tried (with a sensible strategy) by the caller.
func (b *Backend) Remove(snapName string) error {
	// TODO this will not be called for the rootfs case where the system
	// has an implicit plug, but needs to be revisited for snaps.
	return nil
}

// NewSpecification returns a new specification associated with this backend.
func (b *Backend) NewSpecification(*interfaces.SnapAppSet,
	interfaces.ConfinementOptions) interfaces.Specification {
	return &Specification{}
}

// SandboxFeatures returns the list of features supported by snapd for ldconfig.
func (b *Backend) SandboxFeatures() []string {
	return []string{"mediated-ldconfig"}
}

func (b *Backend) setupLdconfigCache(spec *Specification) error {
	dir := dirs.SnapLdconfigDir
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("cannot create directory for ldconfig files %q: %s", dir, err)
	}

	// We want the directories always in the same order in the file
	dirs := make([]string, 0, len(spec.libDirs))
	for dir := range spec.libDirs {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)
	content := "# This file is automatically generated by snapd\n"
	content += strings.Join(dirs, "\n")
	content += "\n"

	// TODO this considers only the case when the libraries are exposed to
	// the rootfs. For snaps, we will create files in
	// /var/lib/snapd/ldconfig/ that will be used to generate a cache
	// specific to each snap.
	ldconfigPath := filepath.Join(dir, "snapd.conf")
	err := osutil.EnsureFileState(ldconfigPath, &osutil.MemoryFileState{
		Content: []byte(content),
		Mode:    0644,
	})
	if err != nil && !errors.Is(err, osutil.ErrSameState) {
		return err
	}

	// Re-create cache
	out, stderr, err := osutil.RunSplitOutput("ldconfig")
	if err != nil {
		return osutil.OutputErrCombine(out, stderr, err)
	}

	return nil
}
